
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import pandas as pd
"""from data import *
from data import calcule"""
# Sales data
sales = {
    "revenue": [472 ,356,278, 412, 550, 672],
    "process": ["Processes 1", "Processes 2", "Processes 3", "Processes 4", "Processes 5", "Processes 6"],
    "angles": [0, 1.04719, 2.094395, 3.141592, 4.18879, 5.23598],
    "rotation": [-90, -30, 30, 90, 330, 390, 450],
    "colors": ["#439A97", "#56a8a5", "#6cbdba", "#12b2ed", "#008fc4", "#0a7ca6"]
}

# Table data

table_columns = ["ID", "T_arround Time"]
table_data = [    
    ["Process 1","20"],
    ["Process 2","20"],
    ["Process 3","20"],
    ["Process 4","20"],
    ["Process 5","20"],
    ["Process 6","20"],


]

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\ASUS\Desktop\khalil\Horizon School of Digital Technologies\Operating Systems\Project\Tkinter-Designer-master\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("892x503")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 503,
    width = 892,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    446.0,
    251.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    352.850978593171,
    204.0634002685547,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    702.0000342703089,
    205.01849365234375,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    356.3449241867294,
    373.06097412109375,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    701.3408100036786,
    373.3194885253906,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    146.99999393924054,
    117.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    97.56767822969937,
    277.53221130371094,
    image=image_image_7
)

canvas.create_text(
    8.0,
    167.0,
    anchor="nw",
    text="Number of \nProcesses",
    fill="#C1E9BD",
    font=("FaustinaRoman Regular", 38 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    585.0000048024306,
    117.0,
    image=image_image_8
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    357.94847449676604,
    118.0908761853412,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#917FB3",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=313.9999939392405,
    y=84.0,
    width=87.89696111505106,
    height=66.1817523706824
)
def calcule():
    print("button_1 clicked")
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: calcule,
    relief="flat"
)
button_1.place(
    x=4.99993896484375,
    y=410.0227966308594,
    width=184.4187469482422,
    height=78.43755340576172
)

canvas.create_text(
    35.0,
    422.0,
    anchor="nw",
    text="Submit",
    fill="#C1E9BD",
    font=("FaustinaRoman Regular", 38 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    97.47350396077877,
    301.8481780492158,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#917FB3",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=34.99999027605418,
    y=277.0,
    width=124.94702736944919,
    height=47.69635609843152
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    816.3363780001985,
    118.09772316184016,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#917FB3",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=770.9999939392405,
    y=84.0,
    width=90.67276812191591,
    height=66.19544632368033
)

canvas.create_text(
    21.0,
    89.0,
    anchor="nw",
    text="Entry Time",
    fill="#C1E9BD",
    font=("FaustinaRoman Regular", 38 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    243.0,
    114.0,
    image=image_image_9
)

canvas.create_text(
    434.0,
    89.0,
    anchor="nw",
    text="Execution Time",
    fill="#C1E9BD",
    font=("FaustinaRoman Regular", 35 * -1)
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    446.0,
    34.0,
    image=image_image_10
)

canvas.create_text(
    79.0,
    6.0,
    anchor="nw",
    text="Process Manegment.py",
    fill="#0F0F0F",
    font=("FaustinaRoman Regular", 38 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    834.0,
    204.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    705.0,
    117.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    36.0,
    34.0,
    image=image_image_13
)

canvas.create_text(
    204.0,
    180.0,
    anchor="nw",
    text="Waiting Time",
    fill="#C1E9BD",
    font=("FaustinaRoman Regular", 34 * -1)
)

canvas.create_text(
    526.0,
    177.0,
    anchor="nw",
    text="T_arround Time",
    fill="#C1E9BD",
    font=("FaustinaRoman Regular", 38 * -1)
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    461.0,
    204.0,
    image=image_image_14
)
"""hex_color = 'D660E0'
rgb_color = mcolors.hex2color('#' + hex_color)
rgba_color = rgb_color + (1.0,) """
"""revenue_date=pd.DataFrame("revenue")
revenue_date["time"]=pd.to_datetime["time"]"""
fig_1=Figure(figsize=(2.5 , 2.2) , facecolor="#D660E0")
ax_1=fig_1.add_subplot(projection="polar")
ax_1.set_facecolor("#D660E0")
ax_1.bar(x=sales["angles"],height=sales["revenue"],color=sales["colors"])
ax_1.set_frame_on(False)
ax_1.set_xticks([])
ax_1.tick_params(labelsize=5,colors="white")
ax_1.grid(alpha=0.8)
for angle , label , rotation in zip(sales["angles"] , sales["process"] , sales["rotation"] ):
    ax_1.text(x=angle , y=max(sales["revenue"])+30 ,s=label , rotation =rotation , ha="center" , va="center" , color="white" , fontsize=8)
canvas= FigureCanvasTkAgg(figure=fig_1 , master=window)
canvas.draw()
canvas.get_tk_widget().place(x=220 , y=268)
table=ttk.Treeview(master=window , columns=table_columns , show="headings")
for column in table_columns:
    table.heading(column =column , text=column)
    table.column(column =column , width=70)
for row_data in table_data :
    table.insert(parent="", index="end" , values=row_data)
table.place(x=630 , y=260)
style=ttk.Style()
style.theme_use("default")
style.configure("Treeview" , background="#D660E0" , fieldbackground="#D660E0 " , foreground="white")
style.configure("Treeview.Heading" , background="#D660E0" , fieldbackground="#D660E0 " , foreground="white")
style.map("Treeview" , background=[("selected" , "#C1E9BD")])
window.resizable(False, False)
window.mainloop() 
window.resizable(False, False)
window.mainloop()
